[project]
name = "logify"
version = "0.1.0"
description = "Modern Python Logging Framework"
authors = [
  {name="Madhur Prakash", email="madhurprakash2005@gmail.com"}
]
dependencies = [
  "colorlog",
  "python-json-logger",
  "pyyaml",
  "requests",
  "python-dotenv",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
